default_language_version:
  python: python3

default_stages: [commit, push]

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", "--check"]

  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        args: ["--check"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-copyright]
