# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: QREF
site_description: Quantum Algorithms Represented Topologically
site_author: PsiQuantum Corp.
copyright: Copyright © 2023-2024 PsiQuantum Corp.
repo_url: https://github.com/psiq/qref
nav:
  - index.md
  - format.md
  - Python Library:
      - library/userguide.md
      - API Reference:
          - qref: library/reference/qref.md
          - qref.schema_v1: library/reference/qref.schema_v1.md
          - qref.experimental.rendering: library/reference/qref.experimental.rendering.md
  - development.md
  - design.md
theme:
  name: material
  palette:
    primary: custom
    accent: custom
  features:
    - content.code.copy
extra_css:
  - psidocs.css
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - docs/examples
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - autorefs
  - mike:
      version_selector: true
      canonical_version: latest
  - search
  - link-marker
  - open-in-new-tab
  - mkdocstrings:
      handlers:
        python:
          options:
            annotation_path: full
            heading_level: 1
            show_source: true
            show_signature_annotations: true
            members_order: source
            separate_signature: true
            show_if_no_docstring: true
            show_root_heading: true
            docstring_options:
              ignore_init_summary: true
              merge_init_into_class: true
              show_docstring_returns: true
extra:
  version:
    provider: mike
