name: Release (Manual Trigger)

on:
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment version
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
          skip-github-release: false
          skip-github-pull-request: true

# bumps z in x.y.z if the commit message is: "fix: blah blah blah" (patch)
# bumps y in x.y.z if the commit message is: "feature: blah blah blah" (minor)
# bumps x in x.y.z if the commit message is "fix! or feature!: blah blah blah" (major)