name: Release (Manual Trigger)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please-pr-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment version and create PR
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
          skip-github-release: false
          skip-github-pull-request: true
